# Generated by Django 5.2.11 on 2026-02-06 02:12

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_text',
            field=models.CharField(blank=True, default='View My Work', max_length=50, verbose_name='CTA Button Text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.CharField(blank=True, help_text='Sub-headline or introduction', max_length=250),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(blank=True, help_text='Main headline for the hero section', max_length=100),
        ),
    ]
